version: '3.7'
services:

  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=pass
         - POSTGRES_USER=postgres
         - POSTGRES_DB=testdb
    restart: unless-stopped

# APP*****************************************
  spring_rest_api:
    image: spring_rest_api:latest
    network_mode: bridge
    container_name: spring_rest_api_green
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: